DemoTruongDuLieuDong/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DemoTruongDuLieuDong.Models
{
    public class Product
    {
        public Guid Id { get; set; }
        [Display(Name = "Mã hàng hóa")]
        public string MaHangHoa { get; set; }
        [Display(Name = "Tên hàng hóa")]
        public string TenHangHoa { get; set; }
        [Display(Name = "SL")]
        public string SoLuong { get; set; }
        [Display(Name = "Giá nhập")]
        public double? GiaNhap { get; set; }
        [Display(Name = "Giá bán")]
        public double? GiaBan { get; set; }
        [Display(Name = "Ghi chú")]
        public string GhiChu { get; set; }
        public List<ProductField> ProductFields { get; set; }

        public Product()
        {
            Id = new Guid();
        }
    }
}

DemoTruongDuLieuDong/Controllers/ProductFieldsController.cs
using DemoTruongDuLieuDong.Data.DataContext;
using DemoTruongDuLieuDong.Models;
using DemoTruongDuLieuDong.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoTruongDuLieuDong.Controllers
{
    public class ProductFieldsController : Controller
    {
        private readonly DemoTruongDuLieuDongDbContext _context;

        public ProductFieldsController(DemoTruongDuLieuDongDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var productFields = _context.ProductFields
                .OrderBy(x => x.Index)
                .DistinctBy(x => x.TenTruong)
                .ToList();

            return View(productFields);
        }

        public IActionResult Create()
        {
            var dataTypes = Enum.GetValues(typeof(FieldDataTypeEnum));
            var listKieuDuLieu = new Dictionary<int, string>();
            foreach(var item in dataTypes)
            {
                listKieuDuLieu.Add((int)item, item.ToString());
            }

            var productFields = _context.ProductFields
                .OrderBy(x => x.Index)
                .DistinctBy(x => x.TenTruong)
                .ToList();

            var maxIndex = (productFields.Count > 0) ? productFields.Max(f => f.Index) : 0;

            var listIndex = new Dictionary<float, string>();
            for (int i = 1; i <= maxIndex; i++)
            {
                listIndex.Add(i, "Thứ " + i);
            }

            var newIndex = maxIndex + 1;

            listIndex.Add(newIndex, "Thứ " + newIndex);

            ViewData["KieuDuLieu"] = new SelectList(listKieuDuLieu, "Key", "Value", listKieuDuLieu.First());
            ViewData["Index"] = new SelectList(listIndex, "Key", "Value", newIndex);

            var countProduct = _context.Products.Count();
            if (countProduct == 0)
            {
                ModelState.AddModelError(string.Empty, "Chưa có hàng hóa, không thể tạo trường!");
                ViewData["IsCreate"] = false;
                return View();
            }

            ViewData["IsCreate"] = true;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductField productField)
        {
            var dataTypes = Enum.GetValues(typeof(FieldDataTypeEnum));
            var listKieuDuLieu = new Dictionary<int, string>();
            foreach (var item in dataTypes)
            {
                listKieuDuLieu.Add((int)item, item.ToString());
            }

            var productFields = _context.ProductFields
                .OrderBy(x => x.Index)
                .DistinctBy(x => x.TenTruong)
                .ToList();

            var maxIndex = (productFields.Count > 0) ? productFields.Max(f => f.Index) : 0;

            var listIndex = new Dictionary<float, string>();

            for (int i = 1; i <= maxIndex; i++)
            {
                listIndex.Add(i, "Thứ " + i);
            }

            listIndex.Add(maxIndex + 1, "Thứ " + maxIndex + 1);

            ViewData["KieuDuLieu"] = new SelectList(listKieuDuLieu, "Key", "Value", listKieuDuLieu.First());
            ViewData["Index"] = new SelectList(listIndex, "Key", "Value", productField.Index);

            if (!string.IsNullOrEmpty(productField.TenTruong))
            {
                if (productField.TenTruong.Trim().Contains(" "))
                {
                    ModelState.AddModelError(string.Empty, "Tên trường có chứa khoảng trắng, vui lòng chọn tên khác!");
                    return View(productField);
                }

                if (productFields.Any(x => x.TenTruong.Trim().Equals(productField.TenTruong.Trim()))) {
                    ModelState.AddModelError(string.Empty, "Tên trường đã tồn tại rồi, vui lòng chọn tên khác!");
                    return View(productField);
                }

                foreach (var item in productFields)
                {
                    if (item.Index >= productField.Index)
                    {
                        var nearItems = _context.ProductFields
                            .Where(x => x.Index == item.Index && x.Id != item.Id)
                            .ToList();

                        foreach (var nearItem in nearItems)
                        {
                            nearItem.Index += 1;
                        }

                        _context.ProductFields.UpdateRange(nearItems);

                        item.Index += 1;
                    }
                }

                _context.ProductFields.UpdateRange(productFields);

                if (string.IsNullOrEmpty(productField.TenHienThi))
                    productField.TenHienThi = productField.TenTruong;

                var products = await _context.Products.ToListAsync();
                foreach (var item in products)
                {
                    var productFieldInsert = new ProductField
                    {
                        Id = Guid.NewGuid(),
                        ProductId = item.Id,
                        TenTruong = productField.TenTruong,
                        TenHienThi = productField.TenHienThi,
                        KieuDuLieu = productField.KieuDuLieu,
                        Index = productField.Index
                    };

                    _context.ProductFields.Add(productFieldInsert);
                }
                
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(productField);
        }

        public IActionResult Edit(string tenTruongCu)
        {
            var dataTypes = Enum.GetValues(typeof(FieldDataTypeEnum));
            var listKieuDuLieu = new Dictionary<int, string>();
            foreach (var item in dataTypes)
            {
                listKieuDuLieu.Add((int)item, item.ToString());
            }

            var productField = _context.ProductFields
                .DistinctBy(x => x.TenTruong)
                .FirstOrDefault(x => x.TenTruong.Trim().Equals(tenTruongCu.Trim()));

            var productFields = _context.ProductFields
                .OrderBy(x => x.Index)
                .DistinctBy(x => x.TenTruong)
                .ToList();

            var listIndex = new Dictionary<float, string>();

            foreach (var item in productFields)
            {
                var indexName = "Thứ " + item.Index;

                listIndex.Add(item.Index, indexName);
            }

            ViewData["TenTruongCu"] = tenTruongCu;
            ViewData["KieuDuLieu"] = new SelectList(listKieuDuLieu, "Key", "Value", listKieuDuLieu.First());
            ViewData["Index"] = new SelectList(listIndex, "Key", "Value", productField.Index);

            return View(productField);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string tenTruongCu, ProductField productField)
        {
            // load lại các select list ngoài view khi submit faild
            var dataTypes = Enum.GetValues(typeof(FieldDataTypeEnum));
            var listKieuDuLieu = new Dictionary<int, string>();
            foreach (var item in dataTypes)
            {
                listKieuDuLieu.Add((int)item, item.ToString());
            }

            var productFieldsUnique = _context.ProductFields
                .OrderBy(x => x.Index)
                .DistinctBy(x => x.TenTruong)
                .ToList();

            var listIndex = new Dictionary<float, string>();

            foreach (var item in productFieldsUnique)
            {
                var indexName = "Thứ " + item.Index;

                listIndex.Add(item.Index, indexName);
            }

            ViewData["TenTruongCu"] = tenTruongCu;
            ViewData["KieuDuLieu"] = new SelectList(listKieuDuLieu, "Key", "Value", listKieuDuLieu.First());
            ViewData["Index"] = new SelectList(listIndex, "Key", "Value", productField.Index);

            if (!string.IsNullOrEmpty(productField.TenTruong))
            {
                if (productField.TenTruong.Trim().Contains(" "))
                {
                    ModelState.AddModelError(string.Empty, "Tên trường có chứa khoảng trắng, vui lòng chọn tên khác!");
                    return View(productField);
                }

                if (!productField.TenTruong.Trim().Equals(tenTruongCu.Trim()) && productFieldsUnique.Any(x => x.TenTruong.Trim().Equals(productField.TenTruong.Trim())))
                {
                    ModelState.AddModelError(string.Empty, "Tên trường đã tồn tại rồi, vui lòng chọn tên khác!");
                    return View(productField);
                }

                // cập nhật index các records
                var sourceProductFields = await _context.ProductFields
                    .Where(x => x.TenTruong.Trim().Equals(tenTruongCu.Trim()))
                    .ToListAsync();

                var sourceProductField = sourceProductFields.FirstOrDefault();

                _context.ProductFields.RemoveRange(sourceProductFields);

                var productFieldsIndex = _context.ProductFields
                   .OrderBy(x => x.Index)
                   .DistinctBy(x => x.TenTruong)
                   .ToList();

                foreach (var item in productFieldsIndex)
                {
                    var nearItems = _context.ProductFields
                        .Where(x => x.Index == item.Index && x.Id != item.Id)
                        .ToList();

                    if (sourceProductField.Index < productField.Index)
                    {
                        if (item.Index > sourceProductField.Index && item.Index <= productField.Index)
                        {

DemoTruongDuLieuDong/Controllers/ProductsController.cs
using DemoTruongDuLieuDong.Data.DataContext;
using DemoTruongDuLieuDong.Models;
using DemoTruongDuLieuDong.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace DemoTruongDuLieuDong.Controllers
{
    public class ProductsController : Controller
    {
        private readonly DemoTruongDuLieuDongDbContext _context;

        public ProductsController(DemoTruongDuLieuDongDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _context.Products
                .Include(x => x.ProductFields)
                .ToListAsync();

            return View(products);
        }

        public IActionResult Create()
        {
            var productFields = _context.ProductFields
                .DistinctBy(x => x.TenTruong)
                .ToList();

            var product = new Product
            {
                ProductFields = productFields.Select(x => { x.NoiDung = string.Empty; return x; }).ToList()
            };

            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Product product)
        {
            if (ModelState.IsValid)
            {
                if (product == null)
                {
                    return NotFound();
                }

                product.Id = Guid.NewGuid();

                if (product.ProductFields != null)
                {
                    foreach (var item in product.ProductFields)
                    {
                        item.Id = Guid.NewGuid();
                        item.ProductId = product.Id;
                    }
                }

                _context.Add(product);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(x => x.ProductFields)
                .FirstOrDefaultAsync(x => x.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (product == null)
                    {
                        return NotFound();
                    }

                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExist(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View(product);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(x => x.ProductFields)
                .FirstOrDefaultAsync(x => x.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var product = await _context.Products
                .Include(x => x.ProductFields)
                .FirstOrDefaultAsync(x => x.Id == id);

            _context.Products.Remove(product);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool ProductExist(Guid id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

DemoTruongDuLieuDong/Views/Products/Create.cshtml
@model DemoTruongDuLieuDong.Models.Product

@{
    ViewData["Title"] = "Thêm mới sản phẩm";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaHangHoa" class="control-label"></label>
                <input asp-for="MaHangHoa" class="form-control" />
                <span asp-validation-for="MaHangHoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenHangHoa" class="control-label"></label>
                <input asp-for="TenHangHoa" class="form-control" />
                <span asp-validation-for="TenHangHoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuong" class="control-label"></label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaNhap" class="control-label"></label>
                <input asp-for="GiaNhap" class="form-control" />
                <span asp-validation-for="GiaNhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaBan" class="control-label"></label>
                <input asp-for="GiaBan" class="form-control" />
                <span asp-validation-for="GiaBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GhiChu" class="control-label"></label>
                <input asp-for="GhiChu" class="form-control" />
                <span asp-validation-for="GhiChu" class="text-danger"></span>
            </div>
            @foreach (var item in Model.ProductFields.OrderBy(x => x.Index))
            {
                var index = Model.ProductFields.IndexOf(item);
                <div class="form-group">
                    <label class="control-label">@item.TenHienThi</label>
                    <input asp-for="ProductFields[index].NoiDung" class="form-control" />
                    <input hidden asp-for="ProductFields[index].TenTruong" class="form-control" />
                    <input hidden asp-for="ProductFields[index].TenHienThi" class="form-control" />
                    <input hidden asp-for="ProductFields[index].KieuDuLieu" class="form-control" />
                    <input hidden asp-for="ProductFields[index].Index" class="form-control" />
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Lưu luôn" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoTruongDuLieuDong/Views/Products/Delete.cshtml
@model DemoTruongDuLieuDong.Models.Product

@{
    ViewData["Title"] = "Xóa sản phẩm";
}

<h3>Có chắc muốn xóa không?</h3>
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MaHangHoa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MaHangHoa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TenHangHoa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TenHangHoa)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SoLuong)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GiaNhap)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GiaNhap)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GiaBan)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.GhiChu)
        </dd>
        @foreach (var item in Model.ProductFields)
        {
            <dt class="col-sm-2">
                @item.TenHienThi
            </dt>
            <dd class="col-sm-10">
                @item.NoiDung
            </dd>
        }
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Xóa luôn" class="btn btn-danger btn-sm"/> |
        <a asp-action="Index">Quay lại</a>
    </form>
</div>

DemoTruongDuLieuDong/Views/Products/Edit.cshtml
@model DemoTruongDuLieuDong.Models.Product

@{
    ViewData["Title"] = "Chỉnh sửa sản phẩm";
}

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input hidden asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="MaHangHoa" class="control-label"></label>
                <input asp-for="MaHangHoa" class="form-control" />
                <span asp-validation-for="MaHangHoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenHangHoa" class="control-label"></label>
                <input asp-for="TenHangHoa" class="form-control" />
                <span asp-validation-for="TenHangHoa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SoLuong" class="control-label"></label>
                <input asp-for="SoLuong" class="form-control" />
                <span asp-validation-for="SoLuong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaNhap" class="control-label"></label>
                <input asp-for="GiaNhap" class="form-control" />
                <span asp-validation-for="GiaNhap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaBan" class="control-label"></label>
                <input asp-for="GiaBan" class="form-control" />
                <span asp-validation-for="GiaBan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GhiChu" class="control-label"></label>
                <input asp-for="GhiChu" class="form-control" />
                <span asp-validation-for="GhiChu" class="text-danger"></span>
            </div>
            @foreach (var item in Model.ProductFields.OrderBy(x => x.Index))
            {
                var index = Model.ProductFields.IndexOf(item);
                <div class="form-group">
                    <label class="control-label">@item.TenHienThi</label>
                    <input asp-for="ProductFields[index].NoiDung" class="form-control" />
                    <input hidden asp-for="ProductFields[index].Id" class="form-control" />
                    <input hidden asp-for="ProductFields[index].TenTruong" class="form-control" />
                    <input hidden asp-for="ProductFields[index].TenHienThi" class="form-control" />
                    <input hidden asp-for="ProductFields[index].KieuDuLieu" class="form-control" />
                    <input hidden asp-for="ProductFields[index].Index" class="form-control" />
                </div>
            }
            <div class="form-group">
                <input type="submit" value="Lưu luôn" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Quay lại</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DemoTruongDuLieuDong/Views/Products/Index.cshtml
@model IEnumerable<DemoTruongDuLieuDong.Models.Product>

@{
    ViewData["Title"] = "Danh sách sản phẩm";

    var productFields = (Model.Count() > 0) ? Model.ToList()[0].ProductFields : new List<ProductField>();
}

<p>
    <a asp-controller="Home" asp-action="Index">Quay lại</a> |
    <a asp-action="Create">Thêm mới hàng hóa</a> |
    <a asp-controller="ProductFields" asp-action="Create">Thêm mới trường động</a> |
    <a asp-controller="ProductFields" asp-action="Index">Danh sách các trường động</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MaHangHoa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TenHangHoa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SoLuong)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GiaNhap)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GiaBan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GhiChu)
            </th>
            @foreach (var item in productFields.OrderBy(x => x.Index))
            {
                <th>
                    @item.TenHienThi
                </th>
            }
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaHangHoa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenHangHoa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaNhap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaBan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GhiChu)
            </td>
            @foreach (var field in item.ProductFields.OrderBy(x => x.Index))
            {
                <td>@field.NoiDung</td>
            }

            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>